#!/bin/bash

cd $EXIL_DIR

if [ -s log/exil-server.pid ]; then
	if ps -p $(cat log/exil-server.pid) > /dev/null; then
		echo '[EXIL]' Server running with pid $(cat log/exil-server.pid)
	else
		echo '[EXIL]' Server crashed
	fi
else
	echo '[EXIL]' No server PID file found
fi
