#!/bin/bash

cd $EXIL_DIR

# Switch to production config
sed -i "s/DevelopmentConfig/ProductionConfig/" server/exil.py
# Serve on port 8021
sed -i "s/PORT = 4001/PORT = 8021/" server/exil.py
# Connect to port 8021
sed -i "s/localhost:4001/exil.nathanm.cf:8021/" client/src/index.js
# Webpack build
cd client
yarn install
yarn build
