#!/bin/bash

cd /home/merrilln/exil
if [ -s server/server.pid ]; then
	if ps -p $(cat server/server.pid) > /dev/null; then
		echo '[EXIL]' Server running with pid $(cat server/server.pid)
	else
		echo '[EXIL]' Server crashed
	fi
else
	echo '[EXIL]' No server PID file found
fi
